apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f e2e-test.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: chromedriver
  name: chromedriver
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: chromedriver
status:
  loadBalancer: {}
