apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f dev.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: e2etest
  name: e2etest
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: e2etest
    spec:
      containers:
      - args:
        - bash
        - debugloop.sh
    #    - e2e:chrome
    #    - --
    #    - features/xxxx
        image: docker.io/nathor/e2etest:latest
        name: e2etest
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
          - name: code
            mountPath: /app
      restartPolicy: Always
      volumes:
        - name: code
          hostPath:
            path: /home/hugo/PycharmProjects/AppProject/e2etests
status: {}
