version: '3'
services:
  web:
    build: ./aioverlord-frontend
    command: ["npm", "run", "dev"]
    ports:
     - "8080:8080"
    links:
      - "flask:flask"
  flask:
    build: ./aioverlord-backend
    ports:
     - "5000:5000"
    links:
      - "mongodb:db"
  mongodb:
    image: "mongo:3.5"
    ports:
      - "27017:27017"
