apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: prod
  labels:
    service: flask
  name: flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: flask
    spec:
      containers:
      - image: localhost:5001/backend:latest
        name: flask
        ports:
        - containerPort: 5000
      restartPolicy: Always
