apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: prod
  labels:
   service: db
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
      - image: localhost:5001/mongo:3.5
        name: db
        ports:
        - containerPort: 27017
      restartPolicy: Always
