apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: prod
  labels:
    service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - image: localhost:5001/nginx:latest
        name: web
        ports:
        - containerPort: 80
      initContainers:
      - name: flaskprobe
        image: localhost:5001/aliveprobe:latest
        command: ['sh', '-c','until (curl -s "http://flask:5000/" --max-time 1 | grep "db connection active") ;
                  do echo waiting for flask server; sleep 2; done;']
      restartPolicy: Always




