apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f dev.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - port: 80
  selector:
    io.kompose.service: web
  type: NodePort
status:
  loadBalancer: {}
