apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  #namespace: sede2enamespace
  labels:
    service: chromedriver
  name: chromedriver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: chromedriver
    spec:
      containers:
      - image: localhost:5001/selenium/standalone-chrome-debug:3.8.1-aluminum
    #  - image: docker.io/selenium/standalone-chrome
        name: chromedriver
        ports:
          - containerPort: 5900
      restartPolicy: Always
