apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - args:
        - npm
        - run
        - e2e
        image: localhost:5001/frontend:latest
        name: web
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: code
            mountPath: /app
      initContainers:
      - name: flaskprobe
        image: localhost:5001/aliveprobe:latest
        command: ['sh', '-c','until (curl -s "http://flask:5000/" --max-time 1 | grep "db connection active") ;
                  do echo waiting for flask server; sleep 2; done;']
      restartPolicy: Always
      volumes:
        - name: code
          hostPath:
            path: /home/hugo/PycharmProjects/AppProject/aioverlord-frontend
