apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f dev.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: flask
  name: flask
spec:
  ports:
  - port: 5000
    nodePort: 30500
  selector:
    io.kompose.service: flask
  type: NodePort
status:
  loadBalancer: {}
