apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f dev.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - npm
        - run
        - dev
        image: localhost:5000/frontend:latest
        name: web
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
          - name: code
            mountPath: /app
      restartPolicy: Always
      volumes:
        - name: code
          hostPath:
            path: /home/hugo/PycharmProjects/AppProject/aioverlord-frontend
status: {}
